name: CI on Self-hosted Runner

on:
  push:
    branches:
      - dev      
  workflow_dispatch:  

jobs:
  build:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
    runs-on: self-hosted
    steps:
      - name: Print current branch
        run: echo "Branch is ${{ github.ref }}"

      - name: Deploy based on branch
        run: |
          if [ "${GITHUB_REF##*/}" = "dev" ]; then
            echo "Deploying to dev directory"
            cd /home/weexcel/github-runner
            git pull origin main
          elif [ "${GITHUB_REF##*/}" = "master" ]; then
            echo "Deploying to production directory"
            cd /home/weexcel/prod-deploy-dir
            git pull origin master
          fi
